CREATE DATABASE venue;

USE venue;

CREATE TABLE gymnasium(
id INT NOT NULL AUTO_INCREMENT,
gymnasium_id VARCHAR(32) NOT NULL COMMENT '体育馆id',
`name` VARCHAR(100) NOT NULL COMMENT '名称',
intro VARCHAR(500) COMMENT '简介',
address VARCHAR(100) COMMENT '地址',
img VARCHAR(200) COMMENT '体育馆图片',
create_time LONG COMMENT '创建时间',
update_time LONG COMMENT '修改时间',
PRIMARY KEY(id)
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT="体育场馆表";

CREATE TABLE reserve(
id INT NOT NULL AUTO_INCREMENT,
reserve_id VARCHAR(32) NOT NULL COMMENT '预定id',
start_date LONG NOT NULL COMMENT '开始时间',
end_date LONG NOT NULL COMMENT '结束时间',
gymnasium_id VARCHAR(32) NOT NULL COMMENT '体育馆id',
gymnasium_name VARCHAR(100) NOT NULL COMMENT '体育馆名称',
user_id VARCHAR(32) NOT NULL COMMENT '用户id',
user_name VARCHAR(50) NOT NULL COMMENT '用户名',
create_time LONG COMMENT '创建时间',
update_time LONG COMMENT '修改时间',
PRIMARY KEY(id)
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT="预定表";

CREATE TABLE USER(
id INT NOT NULL AUTO_INCREMENT,
user_id VARCHAR(32) NOT NULL COMMENT '用户id',
`name` VARCHAR(50) NOT NULL COMMENT '用户名称',
phone VARCHAR(11) NOT NULL COMMENT '用户手机号',
`password` VARCHAR(32) NOT NULL COMMENT '登录密码',
realname VARCHAR(50) COMMENT '用户真实姓名',
school VARCHAR(100) COMMENT '学校',
major VARCHAR(100) COMMENT '专业',
studentid VARCHAR(20) COMMENT '学号',
create_time LONG COMMENT '创建时间',
update_time LONG COMMENT '修改时间',
PRIMARY KEY(id)
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT="用户表";

CREATE TABLE admin(
id INT NOT NULL AUTO_INCREMENT,
`name` VARCHAR(16) NOT NULL COMMENT '登录名',
`password` VARCHAR(32) NOT NULL COMMENT '登录密码',
PRIMARY KEY(id)
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT="管理员表";

CREATE TABLE news(
id INT NOT NULL AUTO_INCREMENT,
news_id VARCHAR(32) NOT NULL COMMENT '新闻id',
title VARCHAR(100) NOT NULL COMMENT '新闻标题',
content TEXT COMMENT '新闻内容',
create_time LONG COMMENT '创建时间',
update_time LONG COMMENT '修改时间',
gymnasium_id VARCHAR(32) NOT NULL COMMENT '体育馆id',
gymnasium_name VARCHAR(100) NOT NULL COMMENT '体育馆名称',
PRIMARY KEY(id)
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT="新闻表";